pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }
    stages {
        stage('Install Dependencies') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('stor') {
                    sh 'npm install'
                }
            }
        }
        
//         stage('Linting') {
//             agent {
//                 docker {
//                     image 'node:16-alpine'
//                 }
//             }
//             steps {
//                 dir('stor') {
//                     sh 'npm install eslint --save-dev' // Install ESLint as a dev dependency (if not already installed)
//                     sh 'npx eslint . --format junit --output-file eslint-results.xml'
//                 }
//             }
//             post {
//                 always {
//                     junit 'stor/eslint-results.xml'
//                 }
//             }
//         }
        
        stage(' Tests ') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('stor') {
                    sh 'npm run test'
                }
            }
        }
    }
    
    post {
        always {
            sh 'docker images -q | xargs docker rmi -f || true'
        }
    }
}
