pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }
    stages {
        stage('Install Dependencies') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
        stage(' Linting ') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('Frontend') {
                    sh 'npm run lint'
                }
            }
        stage(' Tests ') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('Frontend') {
                    sh 'npm run test'
                }
            }
             post {
                 always {
                     junit 'frontend/test-report.html'
                 }
            }
        }
    }
    post {
        always {
            sh 'docker images -q | xargs docker rmi -f || true'
        }
    }
}
