pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }
    stages {
        stage('Install Dependencies') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('stor') {
                    sh 'npm install'
                }
            }
        }
        stage('Linting') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('stor') {
                    sh 'npm run lint'
                }
            }
            post {
                always {
                    junit 'stor/eslint-results.xml'
                }
            }
        }
        stage('Run Jest Tests') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                dir('stor') {
                    sh 'npm run test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build('stor-docker-image', '.')
                    dockerImage.push()
                }
            }
        }
        
    }
    post {
        always {
            sh 'docker images -q | xargs docker rmi -f || true'
        }
    }
}
